/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AllocationRouteImport } from './routes/allocation'
import { Route as BillRouteImport } from './routes/bill'
import { Route as CalcRouteImport } from './routes/calc'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as OwnerIndexRouteImport } from './routes/owner.index'
import { Route as OwnerVerifyRouteImport } from './routes/owner.verify'
import { Route as ReadingIndexRouteImport } from './routes/reading.index'
import { Route as ReadingReviewRouteImport } from './routes/reading.review'
import { Route as TenantIndexRouteImport } from './routes/tenant.index'
import { Route as TenantPaymentRouteImport } from './routes/tenant.payment'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AllocationRoute = AllocationRouteImport.update({
  id: '/allocation',
  path: '/allocation',
  getParentRoute: () => rootRouteImport,
} as any)
const BillRoute = BillRouteImport.update({
  id: '/bill',
  path: '/bill',
  getParentRoute: () => rootRouteImport,
} as any)
const CalcRoute = CalcRouteImport.update({
  id: '/calc',
  path: '/calc',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerIndexRoute = OwnerIndexRouteImport.update({
  id: '/owner/',
  path: '/owner/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerVerifyRoute = OwnerVerifyRouteImport.update({
  id: '/owner/verify',
  path: '/owner/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadingIndexRoute = ReadingIndexRouteImport.update({
  id: '/reading/',
  path: '/reading/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadingReviewRoute = ReadingReviewRouteImport.update({
  id: '/reading/review',
  path: '/reading/review',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantIndexRoute = TenantIndexRouteImport.update({
  id: '/tenant/',
  path: '/tenant/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantPaymentRoute = TenantPaymentRouteImport.update({
  id: '/tenant/payment',
  path: '/tenant/payment',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/allocation': typeof AllocationRoute
  '/bill': typeof BillRoute
  '/calc': typeof CalcRoute
  '/history': typeof HistoryRoute
  '/owner/verify': typeof OwnerVerifyRoute
  '/reading/review': typeof ReadingReviewRoute
  '/tenant/payment': typeof TenantPaymentRoute
  '/owner/': typeof OwnerIndexRoute
  '/reading/': typeof ReadingIndexRoute
  '/tenant/': typeof TenantIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/allocation': typeof AllocationRoute
  '/bill': typeof BillRoute
  '/calc': typeof CalcRoute
  '/history': typeof HistoryRoute
  '/owner/verify': typeof OwnerVerifyRoute
  '/reading/review': typeof ReadingReviewRoute
  '/tenant/payment': typeof TenantPaymentRoute
  '/owner': typeof OwnerIndexRoute
  '/reading': typeof ReadingIndexRoute
  '/tenant': typeof TenantIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/allocation': typeof AllocationRoute
  '/bill': typeof BillRoute
  '/calc': typeof CalcRoute
  '/history': typeof HistoryRoute
  '/owner/verify': typeof OwnerVerifyRoute
  '/reading/review': typeof ReadingReviewRoute
  '/tenant/payment': typeof TenantPaymentRoute
  '/owner/': typeof OwnerIndexRoute
  '/reading/': typeof ReadingIndexRoute
  '/tenant/': typeof TenantIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/allocation'
    | '/bill'
    | '/calc'
    | '/history'
    | '/owner/verify'
    | '/reading/review'
    | '/tenant/payment'
    | '/owner/'
    | '/reading/'
    | '/tenant/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/allocation'
    | '/bill'
    | '/calc'
    | '/history'
    | '/owner/verify'
    | '/reading/review'
    | '/tenant/payment'
    | '/owner'
    | '/reading'
    | '/tenant'
  id:
    | '__root__'
    | '/'
    | '/allocation'
    | '/bill'
    | '/calc'
    | '/history'
    | '/owner/verify'
    | '/reading/review'
    | '/tenant/payment'
    | '/owner/'
    | '/reading/'
    | '/tenant/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AllocationRoute: typeof AllocationRoute
  BillRoute: typeof BillRoute
  CalcRoute: typeof CalcRoute
  HistoryRoute: typeof HistoryRoute
  OwnerVerifyRoute: typeof OwnerVerifyRoute
  ReadingReviewRoute: typeof ReadingReviewRoute
  TenantPaymentRoute: typeof TenantPaymentRoute
  OwnerIndexRoute: typeof OwnerIndexRoute
  ReadingIndexRoute: typeof ReadingIndexRoute
  TenantIndexRoute: typeof TenantIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/allocation': {
      id: '/allocation'
      path: '/allocation'
      fullPath: '/allocation'
      preLoaderRoute: typeof AllocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bill': {
      id: '/bill'
      path: '/bill'
      fullPath: '/bill'
      preLoaderRoute: typeof BillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calc': {
      id: '/calc'
      path: '/calc'
      fullPath: '/calc'
      preLoaderRoute: typeof CalcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/': {
      id: '/owner/'
      path: '/owner'
      fullPath: '/owner/'
      preLoaderRoute: typeof OwnerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/verify': {
      id: '/owner/verify'
      path: '/owner/verify'
      fullPath: '/owner/verify'
      preLoaderRoute: typeof OwnerVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reading/': {
      id: '/reading/'
      path: '/reading'
      fullPath: '/reading/'
      preLoaderRoute: typeof ReadingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reading/review': {
      id: '/reading/review'
      path: '/reading/review'
      fullPath: '/reading/review'
      preLoaderRoute: typeof ReadingReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/': {
      id: '/tenant/'
      path: '/tenant'
      fullPath: '/tenant/'
      preLoaderRoute: typeof TenantIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/payment': {
      id: '/tenant/payment'
      path: '/tenant/payment'
      fullPath: '/tenant/payment'
      preLoaderRoute: typeof TenantPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AllocationRoute: AllocationRoute,
  BillRoute: BillRoute,
  CalcRoute: CalcRoute,
  HistoryRoute: HistoryRoute,
  OwnerVerifyRoute: OwnerVerifyRoute,
  ReadingReviewRoute: ReadingReviewRoute,
  TenantPaymentRoute: TenantPaymentRoute,
  OwnerIndexRoute: OwnerIndexRoute,
  ReadingIndexRoute: ReadingIndexRoute,
  TenantIndexRoute: TenantIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
