/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BillRouteImport } from './routes/bill'
import { Route as OwnerIndexRouteImport } from './routes/owner.index'
import { Route as ReadingIndexRouteImport } from './routes/reading.index'
import { Route as ReadingReviewRouteImport } from './routes/reading.review'
import { Route as TenantIndexRouteImport } from './routes/tenant.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BillRoute = BillRouteImport.update({
  id: '/bill',
  path: '/bill',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerIndexRoute = OwnerIndexRouteImport.update({
  id: '/owner/',
  path: '/owner/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadingIndexRoute = ReadingIndexRouteImport.update({
  id: '/reading/',
  path: '/reading/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadingReviewRoute = ReadingReviewRouteImport.update({
  id: '/reading/review',
  path: '/reading/review',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantIndexRoute = TenantIndexRouteImport.update({
  id: '/tenant/',
  path: '/tenant/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bill': typeof BillRoute
  '/reading/review': typeof ReadingReviewRoute
  '/owner/': typeof OwnerIndexRoute
  '/reading/': typeof ReadingIndexRoute
  '/tenant/': typeof TenantIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bill': typeof BillRoute
  '/reading/review': typeof ReadingReviewRoute
  '/owner': typeof OwnerIndexRoute
  '/reading': typeof ReadingIndexRoute
  '/tenant': typeof TenantIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bill': typeof BillRoute
  '/reading/review': typeof ReadingReviewRoute
  '/owner/': typeof OwnerIndexRoute
  '/reading/': typeof ReadingIndexRoute
  '/tenant/': typeof TenantIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/bill' | '/reading/review' | '/owner/' | '/reading/' | '/tenant/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bill' | '/reading/review' | '/owner' | '/reading' | '/tenant'
  id:
    | '__root__'
    | '/'
    | '/bill'
    | '/reading/review'
    | '/owner/'
    | '/reading/'
    | '/tenant/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BillRoute: typeof BillRoute
  ReadingReviewRoute: typeof ReadingReviewRoute
  OwnerIndexRoute: typeof OwnerIndexRoute
  ReadingIndexRoute: typeof ReadingIndexRoute
  TenantIndexRoute: typeof TenantIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bill': {
      id: '/bill'
      path: '/bill'
      fullPath: '/bill'
      preLoaderRoute: typeof BillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/': {
      id: '/owner/'
      path: '/owner'
      fullPath: '/owner/'
      preLoaderRoute: typeof OwnerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reading/': {
      id: '/reading/'
      path: '/reading'
      fullPath: '/reading/'
      preLoaderRoute: typeof ReadingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reading/review': {
      id: '/reading/review'
      path: '/reading/review'
      fullPath: '/reading/review'
      preLoaderRoute: typeof ReadingReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/': {
      id: '/tenant/'
      path: '/tenant'
      fullPath: '/tenant/'
      preLoaderRoute: typeof TenantIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BillRoute: BillRoute,
  ReadingReviewRoute: ReadingReviewRoute,
  OwnerIndexRoute: OwnerIndexRoute,
  ReadingIndexRoute: ReadingIndexRoute,
  TenantIndexRoute: TenantIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
